# Generated by Django 2.1.3 on 2019-01-07 11:31

import agri_crawler.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dailyEconomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=130)),
                ('sub_body', djongo.models.fields.EmbeddedModelField(model_container=agri_crawler.models.title, model_form_class=agri_crawler.models.titleForm, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='daum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=130)),
                ('sub_body', djongo.models.fields.EmbeddedModelField(model_container=agri_crawler.models.title, model_form_class=agri_crawler.models.titleForm, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='daum_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('sub_body', djongo.models.fields.EmbeddedModelField(model_container=agri_crawler.models.title, model_form_class=agri_crawler.models.titleForm, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='webapp/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='eDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=130)),
                ('sub_body', djongo.models.fields.EmbeddedModelField(model_container=agri_crawler.models.title, model_form_class=agri_crawler.models.titleForm, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JTBC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=130)),
                ('sub_body', djongo.models.fields.EmbeddedModelField(model_container=agri_crawler.models.title, model_form_class=agri_crawler.models.titleForm, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('sub_body', djongo.models.fields.EmbeddedModelField(model_container=agri_crawler.models.title, model_form_class=agri_crawler.models.titleForm, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='koreaEconomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=130)),
                ('sub_body', djongo.models.fields.EmbeddedModelField(model_container=agri_crawler.models.title, model_form_class=agri_crawler.models.titleForm, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MBC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('sub_body', djongo.models.fields.EmbeddedModelField(model_container=agri_crawler.models.title, model_form_class=agri_crawler.models.titleForm, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='moneyToday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=130)),
                ('sub_body', djongo.models.fields.EmbeddedModelField(model_container=agri_crawler.models.title, model_form_class=agri_crawler.models.titleForm, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='naver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=130)),
                ('sub_body', djongo.models.fields.EmbeddedModelField(model_container=agri_crawler.models.title, model_form_class=agri_crawler.models.titleForm, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('sub_body', djongo.models.fields.EmbeddedModelField(model_container=agri_crawler.models.title, model_form_class=agri_crawler.models.titleForm, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='seoulEconomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=130)),
                ('sub_body', djongo.models.fields.EmbeddedModelField(model_container=agri_crawler.models.title, model_form_class=agri_crawler.models.titleForm, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='state1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=100)),
                ('keyword', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('today_date', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100, null=True)),
                ('type_state', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=100)),
                ('keyword', models.CharField(max_length=100)),
                ('sub_body', djongo.models.fields.EmbeddedModelField(model_container=agri_crawler.models.title, model_form_class=agri_crawler.models.titleForm, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YTN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=130)),
                ('sub_body', djongo.models.fields.EmbeddedModelField(model_container=agri_crawler.models.title, model_form_class=agri_crawler.models.titleForm, null=True)),
            ],
        ),
    ]
