# Generated by Django 2.1.3 on 2019-01-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='naver',
            name='main_url',
            field=models.CharField(max_length=130, null=True),
        ),
    ]
