# Generated by Django 2.1.3 on 2019-01-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_crawler', '0003_daum_blog_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='daum_blog',
            name='comment',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
