# Generated by Django 2.1.2 on 2019-01-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_crawler', '0005_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter',
            name='userId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='Id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='content',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
