# Generated by Django 2.1.2 on 2019-02-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_crawler', '0007_auto_20190201_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='naver',
            name='nickname',
            field=models.CharField(max_length=130, null=True),
        ),
    ]
