# Generated by Django 2.1.2 on 2019-02-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_crawler', '0008_naver_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='koreaeconomy',
            name='nickname',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='koreaeconomy',
            name='keyword',
            field=models.CharField(max_length=130, null=True),
        ),
    ]
