# Generated by Django 2.1.2 on 2019-02-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_crawler', '0009_auto_20190201_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyeconomy',
            name='nickname',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='edaily',
            name='nickname',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='jtbc',
            name='nickname',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='kbs',
            name='nickname',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='mbc',
            name='nickname',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='moneytoday',
            name='nickname',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='sbs',
            name='nickname',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='seouleconomy',
            name='nickname',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='ytn',
            name='nickname',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='dailyeconomy',
            name='keyword',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='edaily',
            name='keyword',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='jtbc',
            name='keyword',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='kbs',
            name='keyword',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='mbc',
            name='keyword',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='moneytoday',
            name='keyword',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='sbs',
            name='keyword',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='seouleconomy',
            name='keyword',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='ytn',
            name='keyword',
            field=models.CharField(max_length=130, null=True),
        ),
    ]
