# Generated by Django 2.1.2 on 2019-02-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_crawler', '0011_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='user_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='key',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='value',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
