# Generated by Django 2.1.2 on 2019-02-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_crawler', '0014_remove_state1_total_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=200, null=True)),
                ('naver_count', models.CharField(max_length=200, null=True)),
                ('daum_count', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='news_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=200, null=True)),
                ('kbs_count', models.CharField(max_length=200, null=True)),
                ('mbc_count', models.CharField(max_length=200, null=True)),
                ('sbs_count', models.CharField(max_length=200, null=True)),
                ('jtbc_count', models.CharField(max_length=200, null=True)),
                ('ytn_count', models.CharField(max_length=200, null=True)),
                ('money_count', models.CharField(max_length=200, null=True)),
                ('edaily_count', models.CharField(max_length=200, null=True)),
                ('korea_count', models.CharField(max_length=200, null=True)),
                ('dailyeconomy_count', models.CharField(max_length=200, null=True)),
                ('seouleconomy_count', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='twitter_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=200, null=True)),
                ('twitter_count', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
