# Generated by Django 2.1.2 on 2019-02-13 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agri_crawler', '0015_blog_count_news_count_twitter_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog_count',
        ),
    ]
