# Generated by Django 2.1.2 on 2019-02-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_crawler', '0016_delete_blog_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='daum_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=200, null=True)),
                ('daum_count', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='naver_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=200, null=True)),
                ('naver_count', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
